// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxibkvhnusmnugnmjkxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aWJrdmhudXNtbnVnbm1qa3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDIxNzMsImV4cCI6MjA2NTQ3ODE3M30.g2iQPO1u1j8GWYvzXqn74oC2j6ThoDpEI_vGEx3Us5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);